/** Demo queue rows for configurator preview (demo=1). */
export function buildDemoQueue() {
  return [
    {
      position: 1,
      trackId: "demo-1",
      title: "Live Forever",
      artist: "Headhunterz",
      album: "Hard With Style",
      duration: "3:30",
      requester: "Inzaniity",
      requesterAvatar: "",
      requesterDisplay: "Inzaniity",
      requesterSource: "youtube",
      albumArt: "https://i.scdn.co/image/ab67616d0000b273e5c0984cba590108b93e45d3",
      isLiked: true,
      isSR: true,
    },
    {
      position: 2,
      trackId: "demo-2",
      title: "Pull Up",
      artist: "Snavs",
      album: "Pull Up",
      duration: "2:49",
      requester: "Spotify",
      requesterAvatar: "",
      requesterDisplay: "Spotify",
      albumArt: "https://i.scdn.co/image/ab67616d0000b273c536d5bec433a7db23570c5e",
      isLiked: true,
      isSR: false,
    },
    {
      position: 3,
      trackId: "demo-3",
      title: "All Too Late",
      artist: "IMANU, Rhode",
      album: "Unfold",
      duration: "3:36",
      requester: "Spotify",
      requesterAvatar: "",
      requesterDisplay: "Spotify",
      albumArt: "https://i.scdn.co/image/ab67616d0000b273cae0db665b349fec3c00d4b4",
      isLiked: true,
      isSR: false,
    },
    {
      position: 4,
      trackId: "demo-4",
      title: "Sick",
      artist: "Jauz, FRANK ZUMMO",
      album: "Sick",
      duration: "3:49",
      requester: "viewer123",
      requesterAvatar: "",
      requesterDisplay: "viewer123",
      requesterSource: "spotify",
      albumArt: "https://i.scdn.co/image/ab67616d0000b273c9efc1badc5f4aeceff89e1a",
      isLiked: false,
      isSR: true,
    },
    {
      position: 5,
      trackId: "demo-5",
      title: "Ravers Paradise",
      artist: "HOLY PRIEST",
      album: "Ravers Paradise",
      duration: "2:49",
      requester: "Spotify",
      requesterAvatar: "",
      requesterDisplay: "Spotify",
      albumArt: "https://i.scdn.co/image/ab67616d0000b2730eba6ac37af55d285a66eddd",
      isLiked: true,
      isSR: false,
    },
  ];
}
